### ISSUE TITLE
Consider removing unnecessary content from PR template and convert to embedded comment

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/.github#11]
## Front matter

Why are we using this front matter which adds no value to the PR description, but confusion and additional lines to change while opening the PR?

https://github.com/eclipse-tractusx/.github/blob/3ba80ab1469dcd10c009888766a4787679d01aba/.github/pull_request_template.md?plain=1#L1-L5

If you want the PR authors to use a specific format, eg for the PR title use a PR linter. An example implementation can be found here: [eclipse-tractusx/tractusx-quality-checks/.github/pullRequest-lint.yaml
](https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/.github/workflows/pullRequest-lint.yaml)

## Section: Description
I'd tend to remove the hole section as the complete input is considered as description. If a contributor is using extended commit messages to prepare the PR description, the commit message will be used as PR title, and the extended commit message will be used in the PR description which will be added at the top of the PR description (not under your Description section) → manual editing is required by PR author. 

https://github.com/eclipse-tractusx/.github/blob/3ba80ab1469dcd10c009888766a4787679d01aba/.github/pull_request_template.md?plain=1#L7-L12

Convert section content into a embedded comment if you want to provide these content anyway, and remove heading.

## Section: Additional information

This section makes the PR description bigger than needed an adds no value to the PR description itself. Add/convert these information as embedded comment into the PR template instead. The PR author will see these hints, but they won't appear in the PR itself.

https://github.com/eclipse-tractusx/.github/blob/3ba80ab1469dcd10c009888766a4787679d01aba/.github/pull_request_template.md?plain=1#L21-L27

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/.github/pull/12

**Comment by SebastianBezold** [comment]
I merged #12, since it is already an enhancement to the current workflow. There where some comment on how to make it even better, so i think we can keep this issue open and have a discussion on it before closing the issue

**Comment by FaGru3n** [comment]
@SebastianBezold thanks for merging, are there theese comments to make it even better anywhere stated or i can also find them, or should we discuss it in an open round?

**Comment by FaGru3n** [comment]
Hi @carslen would close this issue after some disscussion on that

If we have more things to change or some other improvments we can just raise annother issue 😉
