### ISSUE TITLE
Create an issue template to track 3rd-party dependency IP issues

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/.github#2]
We should define an organization wide issue template that can be used to track IP issues created by the dash tool.

Information that should be contained:
- Links to the GitLab issues
- Info on 'ability to merge'. I.e. `restricted` but issue number, non `rejected` ...

**Comment by FaGru3n** [comment]
Hi @SebastianBezold,

Would this not mean you have a GitLab and a GitHub issue?

Do we need more information that is allready on our page?
https://eclipse-tractusx.github.io/docs/oss/issues#eclipse-gitlab-ip-issue-tracker

Could we have a little meeting for creation of the available options?

**Comment by SebastianBezold** [comment]
Hi @FaGru3n, 
yes we would have two tickets. The IP issues in Gitlab are created by dash and in the past I also mentioned them in the PR with new dependencies, that I was reviewing.

**Comment by FaGru3n** [comment]
@SebastianBezold  Thanks for the input, updated my dragt PR as ready for review:

modified the information in the template a bit to make it clear what is information sharing and what is really needed like suggested:

> * Links to the GitLab issues
> * Info on 'ability to merge'. I.e. `restricted` but issue number, non `rejected` ...

maybe you can disscuss with me the wording for the explaination for each section

**Comment by SebastianBezold** [comment]
Hi @FaGru3n,

I don't think we need an issue template. Like mentioned, the links are added to a PR directly instead of a separate issue.
Will close this issue here. Was just an idea back then, but working with this more regularly brought me to the conclusion, that separate tasks would just be overhead
